#!/bin/bash

# Script to deploy Firestore indexes

echo "Deploying Firestore indexes..."
echo ""
echo "Make sure you have Firebase CLI installed:"
echo "  npm install -g firebase-tools"
echo ""
echo "Then login to Firebase:"
echo "  firebase login"
echo ""
echo "Initialize Firebase in this directory (if not already done):"
echo "  firebase init firestore"
echo ""
echo "Deploy the indexes:"
echo "  firebase deploy --only firestore:indexes"
echo ""
echo "Or manually create the following indexes in Firebase Console:"
echo ""
echo "1. Collection: messages"
echo "   Fields: senderId (Ascending), timestamp (Descending)"
echo ""
echo "2. Collection: messages"
echo "   Fields: receiverId (Ascending), timestamp (Descending)"
echo ""
echo "3. Collection: messages"
echo "   Fields: senderId (Ascending), receiverId (Ascending), timestamp (Ascending)"
echo ""
echo "4. Collection: messages"
echo "   Fields: receiverId (Ascending), senderId (Ascending), timestamp (Ascending)"
echo ""
echo "Firebase Console: https://console.firebase.google.com/project/ssu-career-connect/firestore/indexes"
